/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import acciones.proyectos.*;
import analisis.*;
import java.io.StringReader;

/**
 *
 * @author joja
 */
public class GUInicial extends javax.swing.JFrame {

    /**
     * Creates new form GUInicial
     */
    public GUInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTree = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeProyectos = new javax.swing.JTree();
        jTabbedPaneEditor = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaStart = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPaneConsola = new javax.swing.JEditorPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuCompilar = new javax.swing.JMenu();
        jMenuCompilarProyectos = new javax.swing.JMenuItem();
        jMenuCompilarJoja = new javax.swing.JMenuItem();
        jMenuErrores = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTreeProyectos);

        javax.swing.GroupLayout jPanelTreeLayout = new javax.swing.GroupLayout(jPanelTree);
        jPanelTree.setLayout(jPanelTreeLayout);
        jPanelTreeLayout.setHorizontalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        jPanelTreeLayout.setVerticalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jTextAreaStart.setColumns(20);
        jTextAreaStart.setRows(5);
        jScrollPane2.setViewportView(jTextAreaStart);

        jTabbedPaneEditor.addTab("start", jScrollPane2);

        jScrollPane3.setViewportView(jEditorPaneConsola);

        jMenuArchivo.setText("Archivo");
        jMenuBarPrincipal.add(jMenuArchivo);

        jMenuCompilar.setText("Compilar");

        jMenuCompilarProyectos.setText("Proyectos");
        jMenuCompilarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompilarProyectosActionPerformed(evt);
            }
        });
        jMenuCompilar.add(jMenuCompilarProyectos);

        jMenuCompilarJoja.setText("Joja");
        jMenuCompilarJoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompilarJojaActionPerformed(evt);
            }
        });
        jMenuCompilar.add(jMenuCompilarJoja);

        jMenuBarPrincipal.add(jMenuCompilar);

        jMenuErrores.setText("Errores");
        jMenuBarPrincipal.add(jMenuErrores);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCompilarJojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompilarJojaActionPerformed
        String inArchivo = this.jTextAreaStart.getText();
        compilar(inArchivo, "joja");
    }//GEN-LAST:event_jMenuCompilarJojaActionPerformed

    private void jMenuCompilarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompilarProyectosActionPerformed
        String inArchivo = this.jTextAreaStart.getText();
        compilar(inArchivo, "proy");
        Proyecto pro = MetodosProyectos.makeProyecto();
        System.out.println("asd as");
    }//GEN-LAST:event_jMenuCompilarProyectosActionPerformed
    
    public void compilar(String inArchivo, String tipoArchivo){
             
        String clearlyAString ="";
        switch(tipoArchivo)
        {
            case "joja":
                try
                {
                JojaphvizLex jojaLexer = new JojaphvizLex(new StringReader(inArchivo));
                JojaphvizCup jojaParser = new JojaphvizCup(jojaLexer);
                jojaParser.parse();
                }catch (Exception ex){System.out.println(ex.toString());}
                break;
                
                
            case "proy":
                //principal
                try
                {
                ProyectosLex proyLexer = new ProyectosLex(new StringReader(inArchivo));
                ProyectosCup proyParser = new ProyectosCup(proyLexer);
                proyParser.parse();
                }catch (Exception ex){System.out.println(ex.toString());}
                break;
        }
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPaneConsola;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCompilar;
    private javax.swing.JMenuItem jMenuCompilarJoja;
    private javax.swing.JMenuItem jMenuCompilarProyectos;
    private javax.swing.JMenu jMenuErrores;
    private javax.swing.JPanel jPanelTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneEditor;
    private javax.swing.JTextArea jTextAreaStart;
    private javax.swing.JTree jTreeProyectos;
    // End of variables declaration//GEN-END:variables
}
