
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 04 22:47:20 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class C3dSym {
  /* terminals */
  public static final int tlienzo = 41;
  public static final int tdecimal = 33;
  public static final int tigual = 27;
  public static final int tpotencia = 43;
  public static final int tmas = 9;
  public static final int tfloattoint = 31;
  public static final int tmethod = 3;
  public static final int tcc = 22;
  public static final int tif = 8;
  public static final int tpor = 11;
  public static final int tca = 21;
  public static final int tmenorigual = 15;
  public static final int tdividir = 12;
  public static final int tconca = 30;
  public static final int tovalo = 39;
  public static final int tlc = 24;
  public static final int tcall = 4;
  public static final int tla = 23;
  public static final int tmenos = 10;
  public static final int tmenor = 13;
  public static final int tstack = 7;
  public static final int tarco = 37;
  public static final int tmayorigual = 16;
  public static final int theap = 6;
  public static final int tmayor = 14;
  public static final int tcoma = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int timprimir = 35;
  public static final int ttexto = 42;
  public static final int tiden = 29;
  public static final int tgoto = 2;
  public static final int trectangulo = 38;
  public static final int tlinea = 36;
  public static final int tigualigual = 17;
  public static final int tthen = 5;
  public static final int tdospuntos = 25;
  public static final int tcallf = 34;
  public static final int tpoligono = 40;
  public static final int tentero = 28;
  public static final int tdiferente = 18;
  public static final int tpuntocoma = 26;
  public static final int tpc = 20;
  public static final int tpa = 19;
}

