/* The following code was generated by JFlex 1.4.3 on 30/06/14 12:58 AM */

package analisis;
import java_cup.runtime.Symbol;
import java.util.*;
import acciones.jojaphviz.Metodos;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30/06/14 12:58 AM from the specification file
 * <tt>JojaphvizLex.jflex</tt>
 */
public class JojaphvizLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int A = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\66\1\1\1\0\1\66\1\2\22\0\1\66\1\52\1\10"+
    "\1\40\2\0\1\63\1\11\1\53\1\54\1\4\1\44\1\62\1\45"+
    "\1\6\1\3\12\5\1\61\1\0\1\47\1\51\1\50\1\64\1\0"+
    "\1\21\1\25\1\26\1\32\1\31\1\16\1\24\1\27\1\13\1\7"+
    "\1\34\1\17\1\41\1\14\1\20\1\35\1\7\1\23\1\22\1\15"+
    "\1\33\1\36\1\30\1\37\1\42\1\43\1\55\1\0\1\56\1\46"+
    "\1\12\1\0\1\21\1\25\1\26\1\32\1\31\1\16\1\24\1\27"+
    "\1\13\1\7\1\34\1\17\1\41\1\14\1\20\1\35\1\7\1\23"+
    "\1\22\1\15\1\33\1\36\1\30\1\37\1\42\1\43\1\57\1\65"+
    "\1\60\63\0\1\7\21\0\1\7\u1f54\0\1\7\udfe7\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\1\20\10\1\1\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\1\2\0\1\32"+
    "\1\33\2\0\1\34\1\0\1\10\1\35\27\10\1\36"+
    "\5\10\1\0\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\2\3\2\0\1\51\1\52"+
    "\1\53\1\10\1\54\4\10\1\55\30\10\2\0\1\3"+
    "\1\10\1\56\1\57\7\10\1\60\4\10\1\61\3\10"+
    "\1\62\1\63\1\10\1\64\5\10\1\65\1\0\1\10"+
    "\1\66\1\67\1\70\1\71\1\10\1\72\1\73\4\10"+
    "\1\74\1\75\1\10\1\76\5\10\1\0\1\10\1\77"+
    "\1\100\1\101\1\102\6\10\1\103\1\0\3\10\1\104"+
    "\1\105\1\10\1\106\1\107\1\110\1\10\1\111\1\112"+
    "\1\10\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\67\0\156\0\245\0\334\0\u0113\0\67"+
    "\0\u014a\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\67\0\u0604"+
    "\0\u063b\0\u0672\0\u06a9\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\u06e0\0\67\0\u0717\0\u074e\0\u0785"+
    "\0\67\0\67\0\u07bc\0\u0181\0\67\0\u07f3\0\u082a\0\u014a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a"+
    "\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u014a"+
    "\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\u0e9c\0\u0ed3\0\u0f0a\0\u07bc\0\67\0\u014a\0\u0f41"+
    "\0\u014a\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u014a\0\u1054\0\u108b"+
    "\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243"+
    "\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb"+
    "\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3"+
    "\0\u0ed3\0\u15ea\0\u014a\0\u014a\0\u1621\0\u1658\0\u168f\0\u16c6"+
    "\0\u16fd\0\u1734\0\u176b\0\u014a\0\u17a2\0\u17d9\0\u1810\0\u1847"+
    "\0\u014a\0\u187e\0\u18b5\0\u18ec\0\u014a\0\u014a\0\u1923\0\u014a"+
    "\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u014a\0\u1a6d\0\u1aa4"+
    "\0\u014a\0\u014a\0\u014a\0\u014a\0\u1adb\0\u014a\0\u014a\0\u1b12"+
    "\0\u1b49\0\u1b80\0\u1bb7\0\u014a\0\u014a\0\u1bee\0\u014a\0\u1c25"+
    "\0\u1c5c\0\u1c93\0\u1cca\0\u1d01\0\u1d38\0\u1d6f\0\u014a\0\u014a"+
    "\0\u014a\0\u014a\0\u1da6\0\u1ddd\0\u1e14\0\u1e4b\0\u1e82\0\u1eb9"+
    "\0\u014a\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95\0\u014a\0\u014a\0\u1fcc"+
    "\0\u014a\0\67\0\u014a\0\u2003\0\u014a\0\u014a\0\u203a\0\u014a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\11\1\25\1\26\1\11"+
    "\1\27\1\30\1\31\2\11\1\32\1\33\1\11\1\34"+
    "\3\11\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\4\71\0\1\4\63\0\1\4"+
    "\3\0\1\57\1\60\44\0\1\61\66\0\1\62\22\0"+
    "\1\7\1\63\65\0\1\11\1\0\1\11\2\0\26\11"+
    "\1\0\3\11\23\0\1\64\1\0\6\64\1\65\56\64"+
    "\7\0\1\66\3\0\25\66\1\0\3\66\30\0\1\11"+
    "\1\0\1\11\2\0\2\11\1\67\1\11\1\70\21\11"+
    "\1\0\1\71\2\11\30\0\1\11\1\0\1\11\2\0"+
    "\17\11\1\72\6\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\11\11\1\73\3\11\1\74\1\11\1\75"+
    "\6\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\5\11\1\76\1\77\1\100\16\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\1\11\1\101\24\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\24\11\1\102"+
    "\1\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\11\11\1\103\14\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\3\11\1\104\12\11\1\105\7\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\17\11\1\106"+
    "\6\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\6\11\1\107\2\11\1\110\14\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\5\11\1\111\1\112\1\113"+
    "\5\11\1\114\10\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\15\11\1\115\10\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\5\11\1\116\17\11\1\117"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\6\11"+
    "\1\120\10\11\1\121\6\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\6\11\1\122\2\11\1\123\7\11"+
    "\1\124\4\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\6\11\1\125\17\11\1\0\3\11\36\0\1\126"+
    "\117\0\1\127\4\0\1\130\62\0\1\131\3\0\1\132"+
    "\66\0\1\133\66\0\1\134\66\0\1\135\66\0\1\136"+
    "\100\0\1\137\70\0\1\140\1\0\1\57\1\141\1\142"+
    "\64\57\4\143\1\144\62\143\5\0\1\145\72\0\1\146"+
    "\62\0\1\11\1\0\1\11\2\0\3\11\1\147\22\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\23\11"+
    "\1\150\2\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\16\11\1\151\7\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\21\11\1\152\4\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\1\11\1\153\24\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\25\11"+
    "\1\154\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\6\11\1\155\17\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\11\11\1\156\14\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\5\11\1\157\20\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\2\11\1\160"+
    "\14\11\1\161\6\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\7\11\1\162\16\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\11\11\1\163\2\11\1\164"+
    "\11\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\11\11\1\165\14\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\1\11\1\166\24\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\3\11\1\167\10\11\1\170"+
    "\11\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\6\11\1\171\17\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\17\11\1\172\6\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\7\11\1\173\16\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\2\11\1\174"+
    "\23\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\10\11\1\175\15\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\7\11\1\176\16\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\1\11\1\177\24\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\10\11\1\200"+
    "\15\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\3\11\1\201\22\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\4\11\1\202\21\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\5\11\1\203\20\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\1\11\1\204"+
    "\24\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\13\11\1\205\12\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\1\11\1\206\24\11\1\0\3\11\64\0"+
    "\1\207\26\0\1\141\65\0\4\143\1\210\65\143\1\211"+
    "\1\210\62\143\5\0\1\11\1\0\1\11\2\0\11\11"+
    "\1\212\14\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\17\11\1\213\6\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\10\11\1\214\15\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\3\11\1\215\22\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\7\11"+
    "\1\216\16\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\10\11\1\217\15\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\17\11\1\220\6\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\2\11\1\221\23\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\5\11"+
    "\1\222\20\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\7\11\1\223\16\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\6\11\1\224\17\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\1\11\1\225\24\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\3\11"+
    "\1\226\22\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\21\11\1\227\4\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\3\11\1\230\22\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\5\11\1\231\20\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\7\11"+
    "\1\232\16\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\10\11\1\233\15\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\3\11\1\234\22\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\17\11\1\235\6\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\11\11"+
    "\1\236\14\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\5\11\1\237\20\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\17\11\1\240\6\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\17\11\1\241\6\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\7\11"+
    "\1\242\16\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\1\11\1\243\24\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\24\11\1\244\1\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\5\11\1\245\20\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\20\11"+
    "\1\246\5\11\1\0\3\11\60\0\1\247\31\0\3\143"+
    "\1\141\1\210\62\143\5\0\1\11\1\0\1\11\2\0"+
    "\1\11\1\250\24\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\6\11\1\251\17\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\3\11\1\252\22\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\17\11\1\253"+
    "\6\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\7\11\1\254\16\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\26\11\1\0\2\11\1\255\30\0\1\11"+
    "\1\0\1\11\2\0\6\11\1\256\17\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\26\11\1\0\1\11"+
    "\1\257\1\11\30\0\1\11\1\0\1\11\2\0\2\11"+
    "\1\260\23\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\14\11\1\261\11\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\11\11\1\262\14\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\7\11\1\263\16\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\22\11"+
    "\1\264\3\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\10\11\1\265\15\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\1\11\1\266\24\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\17\11\1\267\6\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\2\11"+
    "\1\270\23\11\1\0\3\11\30\0\1\11\1\0\1\11"+
    "\2\0\21\11\1\271\4\11\1\0\3\11\30\0\1\11"+
    "\1\0\1\11\2\0\12\11\1\272\13\11\1\0\3\11"+
    "\30\0\1\11\1\0\1\11\2\0\7\11\1\273\16\11"+
    "\1\0\3\11\30\0\1\11\1\0\1\11\2\0\1\11"+
    "\1\274\24\11\1\0\3\11\43\0\1\275\53\0\1\11"+
    "\1\0\1\11\2\0\26\11\1\0\1\276\2\11\30\0"+
    "\1\11\1\0\1\11\2\0\6\11\1\277\17\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\12\11\1\300"+
    "\13\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\15\11\1\301\10\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\2\11\1\302\23\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\2\11\1\303\23\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\2\11\1\304"+
    "\23\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\20\11\1\305\5\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\5\11\1\306\20\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\6\11\1\307\17\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\3\11\1\310"+
    "\22\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\14\11\1\311\11\11\1\0\3\11\46\0\1\312\50\0"+
    "\1\11\1\0\1\11\2\0\1\11\1\313\24\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\12\11\1\314"+
    "\13\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\21\11\1\315\4\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\10\11\1\316\15\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\3\11\1\317\22\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\2\11\1\320"+
    "\23\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\17\11\1\321\6\11\1\0\3\11\40\0\1\322\56\0"+
    "\1\11\1\0\1\11\2\0\11\11\1\323\14\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\21\11\1\324"+
    "\4\11\1\0\3\11\30\0\1\11\1\0\1\11\2\0"+
    "\17\11\1\325\6\11\1\0\3\11\30\0\1\11\1\0"+
    "\1\11\2\0\6\11\1\326\17\11\1\0\3\11\30\0"+
    "\1\11\1\0\1\11\2\0\5\11\1\327\20\11\1\0"+
    "\3\11\30\0\1\11\1\0\1\11\2\0\6\11\1\330"+
    "\17\11\1\0\3\11\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8305];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\1\11\26\1\1\11\4\1\10\11"+
    "\1\1\1\11\1\1\2\0\2\11\2\0\1\11\1\0"+
    "\37\1\1\0\13\11\1\1\2\0\1\1\1\11\40\1"+
    "\2\0\36\1\1\0\25\1\1\0\14\1\1\0\7\1"+
    "\1\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[216];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JojaphvizLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JojaphvizLex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 21: 
          { return new Symbol(JojaphvizSym.tlc, yychar,yyline,new String(yytext()));
          }
        case 76: break;
        case 47: 
          { return new Symbol(JojaphvizSym.tthis, yychar, yyline ,new String(yytext()));
          }
        case 77: break;
        case 59: 
          { return new Symbol(JojaphvizSym.tarray, yychar, yyline ,new String(yytext()));
          }
        case 78: break;
        case 15: 
          { return new Symbol(JojaphvizSym.tno, yychar,yyline,new String(yytext()));
          }
        case 79: break;
        case 43: 
          { return new Symbol(JojaphvizSym.tint, yychar, yyline ,new String(yytext()));
          }
        case 80: break;
        case 48: 
          { return new Symbol(JojaphvizSym.tarco, yychar, yyline ,new String(yytext()));
          }
        case 81: break;
        case 39: 
          { return new Symbol(JojaphvizSym.tand, yychar,yyline,new String(yytext()));
          }
        case 82: break;
        case 27: 
          { return new Symbol(JojaphvizSym.tporigual, yychar,yyline,new String(yytext()));
          }
        case 83: break;
        case 5: 
          { return new Symbol(JojaphvizSym.tpor, yychar, yyline ,new String(yytext()));
          }
        case 84: break;
        case 58: 
          { return new Symbol(JojaphvizSym.tovalo, yychar, yyline ,new String(yytext()));
          }
        case 85: break;
        case 37: 
          { return new Symbol(JojaphvizSym.tigualigual, yychar, yyline,new String(yytext()));
          }
        case 86: break;
        case 40: 
          { return new Symbol(JojaphvizSym.tor, yychar,yyline,new String(yytext()));
          }
        case 87: break;
        case 60: 
          { return new Symbol(JojaphvizSym.tbreak, yychar, yyline ,new String(yytext()));
          }
        case 88: break;
        case 49: 
          { return new Symbol(JojaphvizSym.tbool, yychar, yyline ,new String(yytext()));
          }
        case 89: break;
        case 56: 
          { return new Symbol(JojaphvizSym.tfalse, yychar, yyline ,new String(yytext()));
          }
        case 90: break;
        case 13: 
          { return new Symbol(JojaphvizSym.tmayor, yychar, yyline,new String(yytext()));
          }
        case 91: break;
        case 9: 
          { return new Symbol(JojaphvizSym.tmas, yychar, yyline ,new String(yytext()));
          }
        case 92: break;
        case 18: 
          { return new Symbol(JojaphvizSym.tca, yychar,yyline,new String(yytext()));
          }
        case 93: break;
        case 31: 
          { return new Symbol(JojaphvizSym.tmasmas, yychar, yyline ,new String(yytext()));
          }
        case 94: break;
        case 16: 
          { return new Symbol(JojaphvizSym.tpa, yychar,yyline,new String(yytext()));
          }
        case 95: break;
        case 45: 
          { return new Symbol(JojaphvizSym.tfor, yychar, yyline ,new String(yytext()));
          }
        case 96: break;
        case 12: 
          { return new Symbol(JojaphvizSym.tmenor, yychar, yyline,new String(yytext()));
          }
        case 97: break;
        case 52: 
          { return new Symbol(JojaphvizSym.telse, yychar, yyline ,new String(yytext()));
          }
        case 98: break;
        case 8: 
          { return new Symbol(JojaphvizSym.tiden, yychar,yyline,new String(yytext()));
          }
        case 99: break;
        case 24: 
          { return new Symbol(JojaphvizSym.tamp, yychar,yyline,new String(yytext()));
          }
        case 100: break;
        case 38: 
          { return new Symbol(JojaphvizSym.tdiferente, yychar, yyline,new String(yytext()));
          }
        case 101: break;
        case 7: 
          { return new Symbol(JojaphvizSym.tpunto, yychar,yyline,new String(yytext()));
          }
        case 102: break;
        case 29: 
          { return new Symbol(JojaphvizSym.tif, yychar, yyline ,new String(yytext()));
          }
        case 103: break;
        case 44: 
          { return new Symbol(JojaphvizSym.tnew, yychar, yyline ,new String(yytext()));
          }
        case 104: break;
        case 71: 
          { return new Symbol(JojaphvizSym.timport, yychar, yyline ,new String(yytext()));
          }
        case 105: break;
        case 55: 
          { return new Symbol(JojaphvizSym.tfloat, yychar, yyline ,new String(yytext()));
          }
        case 106: break;
        case 36: 
          { return new Symbol(JojaphvizSym.tmayorigual, yychar, yyline,new String(yytext()));
          }
        case 107: break;
        case 51: 
          { return new Symbol(JojaphvizSym.tchar, yychar, yyline ,new String(yytext()));
          }
        case 108: break;
        case 19: 
          { return new Symbol(JojaphvizSym.tcc, yychar,yyline,new String(yytext()));
          }
        case 109: break;
        case 1: 
          { /** rojo **/
                                /** Metodos.agregarErrorLexico( "Error lexico: " + yytext() + " en la linea: " + yyline + " y columna " + yychar); **/
                                /**Metodos.addError("lexico", yyline, yychar, "Caracter no reconocido: " + yytext());**/
                                Metodos.addError("lexico",  "Caracter no reconocido: " + yytext(), String.valueOf(yyline), String.valueOf(yychar));     
                                System.out.println("Error lexico: " + yytext() + " en la linea: " + yyline + " y columna " + yychar);
          }
        case 110: break;
        case 66: 
          { return new Symbol(JojaphvizSym.treturn, yychar, yyline ,new String(yytext()));
          }
        case 111: break;
        case 30: 
          { return new Symbol(JojaphvizSym.tdo, yychar, yyline ,new String(yytext()));
          }
        case 112: break;
        case 68: 
          { return new Symbol(JojaphvizSym.textends, yychar, yyline ,new String(yytext()));
          }
        case 113: break;
        case 63: 
          { return new Symbol(JojaphvizSym.tlienzo, yychar, yyline ,new String(yytext()));
          }
        case 114: break;
        case 41: 
          { return new Symbol(JojaphvizSym.tdecimal, yychar,yyline,new String(yytext()));
          }
        case 115: break;
        case 10: 
          { return new Symbol(JojaphvizSym.tmenos, yychar, yyline ,new String(yytext()));
          }
        case 116: break;
        case 62: 
          { return new Symbol(JojaphvizSym.twhile, yychar, yyline ,new String(yytext()));
          }
        case 117: break;
        case 17: 
          { return new Symbol(JojaphvizSym.tpc, yychar,yyline,new String(yytext()));
          }
        case 118: break;
        case 54: 
          { return new Symbol(JojaphvizSym.ttexto, yychar, yyline ,new String(yytext()));
          }
        case 119: break;
        case 11: 
          { return new Symbol(JojaphvizSym.tpotencia, yychar, yyline ,new String(yytext()));
          }
        case 120: break;
        case 2: 
          { yychar = 0;
                    return new Symbol(JojaphvizSym.tenter, yychar,yyline,new String(yytext()));
          }
        case 121: break;
        case 4: 
          { return new Symbol(JojaphvizSym.tdividir, yychar, yyline ,new String(yytext()));
          }
        case 122: break;
        case 75: 
          { return new Symbol(JojaphvizSym.trectangulo, yychar, yyline ,new String(yytext()));
          }
        case 123: break;
        case 70: 
          { return new Symbol(JojaphvizSym.tprivate, yychar, yyline ,new String(yytext()));
          }
        case 124: break;
        case 69: 
          { return new Symbol(JojaphvizSym.tdefault, yychar, yyline ,new String(yytext()));
          }
        case 125: break;
        case 57: 
          { return new Symbol(JojaphvizSym.tlinea, yychar, yyline ,new String(yytext()));
          }
        case 126: break;
        case 61: 
          { return new Symbol(JojaphvizSym.tclass, yychar, yyline ,new String(yytext()));
          }
        case 127: break;
        case 3: 
          { /* Se ignoran */
          }
        case 128: break;
        case 34: 
          { return new Symbol(JojaphvizSym.tmenosigual, yychar,yyline,new String(yytext()));
          }
        case 129: break;
        case 25: 
          { return new Symbol(JojaphvizSym.tinterrogacion, yychar,yyline,new String(yytext()));
          }
        case 130: break;
        case 72: 
          { return new Symbol(JojaphvizSym.timprimir, yychar, yyline ,new String(yytext()));
          }
        case 131: break;
        case 53: 
          { return new Symbol(JojaphvizSym.tvoid, yychar, yyline ,new String(yytext()));
          }
        case 132: break;
        case 67: 
          { return new Symbol(JojaphvizSym.tpublic, yychar, yyline ,new String(yytext()));
          }
        case 133: break;
        case 6: 
          { return new Symbol(JojaphvizSym.tentero, yychar,yyline,new String(yytext()));
          }
        case 134: break;
        case 73: 
          { return new Symbol(JojaphvizSym.tcontinue, yychar, yyline ,new String(yytext()));
          }
        case 135: break;
        case 33: 
          { return new Symbol(JojaphvizSym.tmenosmenos, yychar, yyline ,new String(yytext()));
          }
        case 136: break;
        case 14: 
          { return new Symbol(JojaphvizSym.tigual, yychar,yyline,new String(yytext()));
          }
        case 137: break;
        case 35: 
          { return new Symbol(JojaphvizSym.tmenorigual, yychar, yyline,new String(yytext()));
          }
        case 138: break;
        case 20: 
          { return new Symbol(JojaphvizSym.tla, yychar,yyline,new String(yytext()));
          }
        case 139: break;
        case 32: 
          { return new Symbol(JojaphvizSym.tmasigual, yychar,yyline,new String(yytext()));
          }
        case 140: break;
        case 64: 
          { return new Symbol(JojaphvizSym.tstring, yychar, yyline ,new String(yytext()));
          }
        case 141: break;
        case 46: 
          { return new Symbol(JojaphvizSym.ttrue, yychar, yyline ,new String(yytext()));
          }
        case 142: break;
        case 42: 
          { return new Symbol(JojaphvizSym.tcaracter, yychar,yyline,new String(yytext().substring(1, yytext().length()-1)));
          }
        case 143: break;
        case 26: 
          { return new Symbol(JojaphvizSym.tdividirigual, yychar,yyline,new String(yytext()));
          }
        case 144: break;
        case 23: 
          { return new Symbol(JojaphvizSym.tcoma, yychar,yyline,new String(yytext()));
          }
        case 145: break;
        case 74: 
          { return new Symbol(JojaphvizSym.tpoligono, yychar, yyline ,new String(yytext()));
          }
        case 146: break;
        case 22: 
          { return new Symbol(JojaphvizSym.tdospuntos, yychar,yyline,new String(yytext()));
          }
        case 147: break;
        case 50: 
          { return new Symbol(JojaphvizSym.tcase, yychar, yyline ,new String(yytext()));
          }
        case 148: break;
        case 65: 
          { return new Symbol(JojaphvizSym.tswitch, yychar, yyline ,new String(yytext()));
          }
        case 149: break;
        case 28: 
          { return new Symbol(JojaphvizSym.tcadena, yychar,yyline,new String(yytext().substring(1, yytext().length()-1)));
          }
        case 150: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(JojaphvizSym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
