
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 04 20:05:18 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class JojaphvizSym {
  /* terminals */
  public static final int tigual = 11;
  public static final int tmenorigual = 47;
  public static final int twhile = 52;
  public static final int tcoma = 12;
  public static final int ttrue = 30;
  public static final int tentero = 26;
  public static final int tovalo = 70;
  public static final int tchar = 16;
  public static final int tmenos = 20;
  public static final int tpotencia = 23;
  public static final int tmenor = 36;
  public static final int tlinea = 66;
  public static final int tbreak = 55;
  public static final int tlienzo = 72;
  public static final int tvoid = 18;
  public static final int tdiferente = 50;
  public static final int tmenosigual = 62;
  public static final int telse = 43;
  public static final int tpunto = 4;
  public static final int trectangulo = 69;
  public static final int tfor = 51;
  public static final int tmasmas = 32;
  public static final int tthis = 38;
  public static final int tmas = 19;
  public static final int tint = 13;
  public static final int tmenosmenos = 33;
  public static final int tswitch = 57;
  public static final int tlc = 10;
  public static final int tenter = 5;
  public static final int tla = 9;
  public static final int tpublic = 6;
  public static final int textends = 41;
  public static final int tmayorigual = 48;
  public static final int treturn = 65;
  public static final int tarco = 68;
  public static final int tdividir = 22;
  public static final int tdecimal = 27;
  public static final int timport = 2;
  public static final int tcase = 59;
  public static final int tdospuntos = 60;
  public static final int tcadena = 28;
  public static final int tdo = 53;
  public static final int timprimir = 73;
  public static final int tporigual = 63;
  public static final int tnew = 54;
  public static final int tdividirigual = 64;
  public static final int tdefault = 58;
  public static final int tand = 45;
  public static final int tigualigual = 49;
  public static final int tbool = 14;
  public static final int EOF = 0;
  public static final int tpc = 25;
  public static final int tstring = 15;
  public static final int tpa = 24;
  public static final int tpoligono = 71;
  public static final int tmayor = 37;
  public static final int tcaracter = 29;
  public static final int ttexto = 67;
  public static final int tamp = 34;
  public static final int tinterrogacion = 74;
  public static final int tor = 44;
  public static final int error = 1;
  public static final int tcc = 40;
  public static final int tiden = 3;
  public static final int tca = 39;
  public static final int tif = 42;
  public static final int tmasigual = 61;
  public static final int tcontinue = 56;
  public static final int tfalse = 31;
  public static final int tarray = 35;
  public static final int tfloat = 17;
  public static final int tprivate = 7;
  public static final int tpor = 21;
  public static final int tno = 46;
  public static final int tclass = 8;
}

