
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 10 21:33:33 CST 2014
//----------------------------------------------------

package analisis;

import java_cup.runtime.*;
import java.util.*;
import acciones.proyectos.*;

/** CUP v0.10k generated parser.
  * @version Tue Jun 10 21:33:33 CST 2014
  */
public class ProyectosCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ProyectosCup() {super();}

  /** Constructor which sets the default scanner. */
  public ProyectosCup(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\003\003\000\002\004" +
    "\003\000\002\005\007\000\002\005\010\000\002\006\004" +
    "\000\002\006\002\000\002\007\006\000\002\010\004\000" +
    "\002\010\002\000\002\011\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\004\004\004\001\002\000\004\005\011\001" +
    "\002\000\004\002\uffff\001\002\000\004\002\010\001\002" +
    "\000\004\002\000\001\002\000\004\002\001\001\002\000" +
    "\010\005\ufff8\006\ufff8\011\ufff8\001\002\000\010\005\015" +
    "\006\014\011\013\001\002\000\004\006\030\001\002\000" +
    "\004\004\ufffb\001\002\000\004\007\017\001\002\000\010" +
    "\005\ufff9\006\ufff9\011\ufff9\001\002\000\004\010\020\001" +
    "\002\000\010\005\ufff7\006\ufff7\011\ufff7\001\002\000\004" +
    "\004\023\001\002\000\006\002\ufffd\004\ufffd\001\002\000" +
    "\006\005\011\011\025\001\002\000\004\004\ufffc\001\002" +
    "\000\004\005\026\001\002\000\004\006\027\001\002\000" +
    "\006\002\ufffa\004\ufffa\001\002\000\006\002\ufffe\004\ufffe" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\010\003\005\004\006\005\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\011\001\001\000" +
    "\004\011\015\001\001\000\002\001\001\000\004\006\020" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\005\023\007\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ProyectosCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ProyectosCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ProyectosCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automaticamente ante algun error sintáctico.*/
    public void syntax_error(Symbol s)
    {
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1) +" Columna "+s.left+ ". Identificador \"" +s.value + "\" no reconocido." );
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    { 
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1)+ " Columna "+s.left+". Identificador \"" + s.value + "\" no reconocido."); 
    }

   

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ProyectosCup$actions {


    boolean correcto = true;

  private final ProyectosCup parser;

  /** Constructor */
  CUP$ProyectosCup$actions(ProyectosCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ProyectosCup$do_action(
    int                        CUP$ProyectosCup$act_num,
    java_cup.runtime.lr_parser CUP$ProyectosCup$parser,
    java.util.Stack            CUP$ProyectosCup$stack,
    int                        CUP$ProyectosCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ProyectosCup$result;

      /* select the action based on the action number */
      switch (CUP$ProyectosCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ATRIBUTO ::= tiden tigual tcadena 
            {
              Object RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		 RESULT = new Atributo((String)n, (String)v); 
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(7/*ATRIBUTO*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ATRIBUTOS ::= 
            {
              Object RESULT = null;
		 RESULT = null; 
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(6/*ATRIBUTOS*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ATRIBUTOS ::= ATRIBUTOS ATRIBUTO 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		 
                        if(l==null){ ArrayList<Instruccion> lista = new ArrayList<>(); lista.add((Instruccion)e); RESULT = lista; } 
                        else { ArrayList<Instruccion> lista = new ArrayList<>(); lista = (ArrayList<Instruccion>)l; lista.add((Instruccion)e); RESULT = lista;  }
                    
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(6/*ATRIBUTOS*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TAG_FINAL ::= tmenor tslash tiden tmayor 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).value;
		  Object[] tagFinal = {e , (Object) (eright +1) , (Object)eleft };
                        RESULT = tagFinal; 
                    
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(5/*TAG_FINAL*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // OBJETOS ::= 
            {
              Object RESULT = null;
		
                            RESULT = null;
                        
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(4/*OBJETOS*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // OBJETOS ::= OBJETOS OBJETO 
            {
              Object RESULT = null;
		int osleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left;
		int osright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).right;
		Object os = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		
                            if(os==null){ 
                            ArrayList<Instruccion> lista = new ArrayList<>(); 
                            lista.add((Instruccion)o); 
                            RESULT = lista; }
 
                            else { ArrayList<Instruccion> lista = new ArrayList<>(); 
                            lista = (ArrayList<Instruccion>)os; 
                            lista.add((Instruccion)o); 
                            RESULT = lista;  }
                        
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(4/*OBJETOS*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // OBJETO ::= tmenor tiden ATRIBUTOS tmayor OBJETOS TAG_FINAL 
            {
              Object RESULT = null;
		int tileft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-4)).left;
		int tiright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-4)).right;
		Object ti = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).value;
		int tfleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int tfright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object tf = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		  Object[] tagFinal =  (Object[]) tf;
                        String tagInicial = (String)ti;
                        if(((String)tagFinal[0]).equals(tagInicial))
                        {
                            RESULT = new Objeto((String)tagFinal[0], (ArrayList<Instruccion>)a, (ArrayList<Instruccion>)o );
                        }
                        else
                        {
                            correcto = false;
                            MetodosProyectos.addError("Semantico",(int)tagFinal[1], (int)tagFinal[2], "Tag de finalización no concuerda. " + "<"+ (String)ti + ">" + " </" + (String)tagFinal[0] + ">" ); 
                            RESULT = new Objeto((String)ti + "-error", null, null);
                        }
                    
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(3/*OBJETO*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-5)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // OBJETO ::= tmenor tiden ATRIBUTOS tslash tmayor 
            {
              Object RESULT = null;
		int tileft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).left;
		int tiright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).right;
		Object ti = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-2)).value;
		
                        RESULT = new Objeto((String)ti, (ArrayList<Instruccion>)a , null);
                    
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(3/*OBJETO*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-4)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CUERPO ::= OBJETO 
            {
              Object RESULT = null;
		int ofleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int ofright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object of = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		 RESULT = of; 
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(2/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CUERPO 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).value;
		 
                            System.out.println("Fin, " + correcto); 
                            MetodosProyectos.objProyectos = (Objeto)e;
                            MetodosProyectos.setCorrecto(correcto);
                            
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          return CUP$ProyectosCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).value;
		RESULT = start_val;
              CUP$ProyectosCup$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$ProyectosCup$stack.elementAt(CUP$ProyectosCup$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$ProyectosCup$parser.done_parsing();
          return CUP$ProyectosCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

