
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 10 21:33:33 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class ProyectosSym {
  /* terminals */
  public static final int tslash = 7;
  public static final int tcadena = 6;
  public static final int tigual = 5;
  public static final int tmenor = 2;
  public static final int error = 1;
  public static final int tmayor = 4;
  public static final int tiden = 3;
  public static final int EOF = 0;
}

