
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 04 22:47:20 CST 2014
//----------------------------------------------------

package analisis;

import java_cup.runtime.*;
import java.util.*;
import acciones.c3d.*;
import acciones.tablasimbolos.MetodosTS;

/** CUP v0.10k generated parser.
  * @version Fri Jul 04 22:47:20 CST 2014
  */
public class C3dCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public C3dCup() {super();}

  /** Constructor which sets the default scanner. */
  public C3dCup(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\003\003\000\002\004" +
    "\003\000\002\005\004\000\002\005\003\000\002\023\002" +
    "\000\002\006\012\000\002\007\004\000\002\007\003\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\013" +
    "\006\000\002\013\011\000\002\013\011\000\002\016\006" +
    "\000\002\016\006\000\002\016\003\000\002\016\005\000" +
    "\002\016\010\000\002\016\006\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\004\000\002\022" +
    "\004\000\002\021\007\000\002\014\012\000\002\014\024" +
    "\000\002\014\032\000\002\014\026\000\002\014\026\000" +
    "\002\014\022\000\002\014\020\000\002\014\022\000\002" +
    "\011\004\000\002\015\012\000\002\012\005\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\017\003\000\002\017\003\000" +
    "\002\017\003\000\002\017\003\000\002\017\003\000\002" +
    "\017\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\341\000\004\005\005\001\002\000\006\002\ufffd\005" +
    "\ufffd\001\002\000\004\037\013\001\002\000\004\002\012" +
    "\001\002\000\006\002\uffff\005\005\001\002\000\004\002" +
    "\000\001\002\000\006\002\ufffe\005\ufffe\001\002\000\004" +
    "\002\001\001\002\000\004\025\014\001\002\000\004\026" +
    "\015\001\002\000\004\031\ufffc\001\002\000\004\031\017" +
    "\001\002\000\020\004\036\006\033\010\021\011\026\012" +
    "\024\037\027\044\022\001\002\000\022\004\ufff9\006\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\032\ufff9\037\ufff9\044\ufff9\001" +
    "\002\000\004\027\336\001\002\000\022\045\143\046\140" +
    "\047\137\050\144\051\136\052\141\053\145\054\142\001" +
    "\002\000\022\004\ufff5\006\ufff5\010\ufff5\011\ufff5\012\ufff5" +
    "\032\ufff5\037\ufff5\044\ufff5\001\002\000\012\014\052\036" +
    "\061\037\056\043\060\001\002\000\022\004\ufff6\006\ufff6" +
    "\010\ufff6\011\ufff6\012\ufff6\032\ufff6\037\ufff6\044\ufff6\001" +
    "\002\000\004\027\113\001\002\000\006\033\050\035\047" +
    "\001\002\000\022\004\ufff4\006\ufff4\010\ufff4\011\ufff4\012" +
    "\ufff4\032\ufff4\037\ufff4\044\ufff4\001\002\000\022\004\ufff8" +
    "\006\ufff8\010\ufff8\011\ufff8\012\ufff8\032\ufff8\037\ufff8\044" +
    "\ufff8\001\002\000\022\004\036\006\033\010\021\011\026" +
    "\012\024\032\046\037\027\044\022\001\002\000\004\037" +
    "\041\001\002\000\022\004\ufff7\006\ufff7\010\ufff7\011\ufff7" +
    "\012\ufff7\032\ufff7\037\ufff7\044\ufff7\001\002\000\022\004" +
    "\ufff3\006\ufff3\010\ufff3\011\ufff3\012\ufff3\032\ufff3\037\ufff3" +
    "\044\ufff3\001\002\000\004\037\037\001\002\000\004\034" +
    "\040\001\002\000\022\004\uffd9\006\uffd9\010\uffd9\011\uffd9" +
    "\012\uffd9\032\uffd9\037\uffd9\044\uffd9\001\002\000\004\025" +
    "\042\001\002\000\004\026\043\001\002\000\004\034\044" +
    "\001\002\000\022\004\uffe4\006\uffe4\010\uffe4\011\uffe4\012" +
    "\uffe4\032\uffe4\037\uffe4\044\uffe4\001\002\000\022\004\ufffa" +
    "\006\ufffa\010\ufffa\011\ufffa\012\ufffa\032\ufffa\037\ufffa\044" +
    "\ufffa\001\002\000\006\002\ufffb\005\ufffb\001\002\000\022" +
    "\010\053\011\055\014\052\036\061\037\056\040\054\041" +
    "\051\043\060\001\002\000\022\004\uffdb\006\uffdb\010\uffdb" +
    "\011\uffdb\012\uffdb\032\uffdb\037\uffdb\044\uffdb\001\002\000" +
    "\004\025\110\001\002\000\006\036\106\043\107\001\002" +
    "\000\004\027\103\001\002\000\004\025\076\001\002\000" +
    "\004\027\073\001\002\000\036\007\uffe7\013\uffe7\014\uffe7" +
    "\015\uffe7\016\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023" +
    "\uffe7\024\uffe7\026\uffe7\034\uffe7\055\uffe7\001\002\000\016" +
    "\013\071\014\065\015\070\016\066\034\uffed\055\067\001" +
    "\002\000\036\007\uffe8\013\uffe8\014\uffe8\015\uffe8\016\uffe8" +
    "\017\uffe8\020\uffe8\021\uffe8\022\uffe8\023\uffe8\024\uffe8\026" +
    "\uffe8\034\uffe8\055\uffe8\001\002\000\036\007\uffe9\013\uffe9" +
    "\014\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9\021\uffe9\022" +
    "\uffe9\023\uffe9\024\uffe9\026\uffe9\034\uffe9\055\uffe9\001\002" +
    "\000\004\034\063\001\002\000\022\004\ufff2\006\ufff2\010" +
    "\ufff2\011\ufff2\012\ufff2\032\ufff2\037\ufff2\044\ufff2\001\002" +
    "\000\012\014\052\036\061\037\056\043\060\001\002\000" +
    "\012\014\uffd7\036\uffd7\037\uffd7\043\uffd7\001\002\000\012" +
    "\014\uffd5\036\uffd5\037\uffd5\043\uffd5\001\002\000\012\014" +
    "\uffd4\036\uffd4\037\uffd4\043\uffd4\001\002\000\012\014\uffd6" +
    "\036\uffd6\037\uffd6\043\uffd6\001\002\000\012\014\uffd8\036" +
    "\uffd8\037\uffd8\043\uffd8\001\002\000\004\034\uffec\001\002" +
    "\000\004\037\074\001\002\000\004\030\075\001\002\000" +
    "\004\034\uffef\001\002\000\004\037\077\001\002\000\004" +
    "\042\100\001\002\000\004\037\101\001\002\000\004\026" +
    "\102\001\002\000\004\034\uffeb\001\002\000\004\037\104" +
    "\001\002\000\004\030\105\001\002\000\004\034\uffee\001" +
    "\002\000\036\007\uffe6\013\uffe6\014\uffe6\015\uffe6\016\uffe6" +
    "\017\uffe6\020\uffe6\021\uffe6\022\uffe6\023\uffe6\024\uffe6\026" +
    "\uffe6\034\uffe6\055\uffe6\001\002\000\036\007\uffe5\013\uffe5" +
    "\014\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022" +
    "\uffe5\023\uffe5\024\uffe5\026\uffe5\034\uffe5\055\uffe5\001\002" +
    "\000\012\014\052\036\061\037\056\043\060\001\002\000" +
    "\004\026\112\001\002\000\004\034\uffea\001\002\000\004" +
    "\037\114\001\002\000\004\030\115\001\002\000\004\035" +
    "\116\001\002\000\012\014\052\036\061\037\056\043\060" +
    "\001\002\000\004\034\120\001\002\000\022\004\ufff1\006" +
    "\ufff1\010\ufff1\011\ufff1\012\ufff1\032\ufff1\037\ufff1\044\ufff1" +
    "\001\002\000\016\017\124\020\125\021\130\022\127\023" +
    "\122\024\126\001\002\000\012\014\uffcf\036\uffcf\037\uffcf" +
    "\043\uffcf\001\002\000\012\014\052\036\061\037\056\043" +
    "\060\001\002\000\012\014\uffd3\036\uffd3\037\uffd3\043\uffd3" +
    "\001\002\000\012\014\uffd2\036\uffd2\037\uffd2\043\uffd2\001" +
    "\002\000\012\014\uffce\036\uffce\037\uffce\043\uffce\001\002" +
    "\000\012\014\uffd0\036\uffd0\037\uffd0\043\uffd0\001\002\000" +
    "\012\014\uffd1\036\uffd1\037\uffd1\043\uffd1\001\002\000\004" +
    "\007\132\001\002\000\004\004\133\001\002\000\004\037" +
    "\134\001\002\000\004\034\135\001\002\000\022\004\uffda" +
    "\006\uffda\010\uffda\011\uffda\012\uffda\032\uffda\037\uffda\044" +
    "\uffda\001\002\000\004\025\314\001\002\000\004\025\266" +
    "\001\002\000\004\025\246\001\002\000\004\025\230\001" +
    "\002\000\004\025\212\001\002\000\004\025\204\001\002" +
    "\000\004\025\162\001\002\000\004\025\146\001\002\000" +
    "\004\037\147\001\002\000\004\042\150\001\002\000\004" +
    "\037\151\001\002\000\004\042\152\001\002\000\004\037" +
    "\153\001\002\000\004\042\154\001\002\000\004\037\155" +
    "\001\002\000\004\042\156\001\002\000\004\037\157\001" +
    "\002\000\004\026\160\001\002\000\004\034\161\001\002" +
    "\000\022\004\uffdd\006\uffdd\010\uffdd\011\uffdd\012\uffdd\032" +
    "\uffdd\037\uffdd\044\uffdd\001\002\000\004\037\163\001\002" +
    "\000\004\042\164\001\002\000\004\037\165\001\002\000" +
    "\004\042\166\001\002\000\004\037\167\001\002\000\004" +
    "\042\170\001\002\000\004\037\171\001\002\000\004\042" +
    "\172\001\002\000\004\037\173\001\002\000\004\042\174" +
    "\001\002\000\004\037\175\001\002\000\004\042\176\001" +
    "\002\000\004\037\177\001\002\000\004\042\200\001\002" +
    "\000\004\037\201\001\002\000\004\026\202\001\002\000" +
    "\004\034\203\001\002\000\022\004\uffe0\006\uffe0\010\uffe0" +
    "\011\uffe0\012\uffe0\032\uffe0\037\uffe0\044\uffe0\001\002\000" +
    "\004\037\205\001\002\000\004\042\206\001\002\000\004" +
    "\036\207\001\002\000\004\026\210\001\002\000\004\034" +
    "\211\001\002\000\022\004\uffe3\006\uffe3\010\uffe3\011\uffe3" +
    "\012\uffe3\032\uffe3\037\uffe3\044\uffe3\001\002\000\004\037" +
    "\213\001\002\000\004\042\214\001\002\000\004\037\215" +
    "\001\002\000\004\042\216\001\002\000\004\037\217\001" +
    "\002\000\004\042\220\001\002\000\004\037\221\001\002" +
    "\000\004\042\222\001\002\000\004\037\223\001\002\000" +
    "\004\042\224\001\002\000\004\037\225\001\002\000\004" +
    "\026\226\001\002\000\004\034\227\001\002\000\022\004" +
    "\uffdc\006\uffdc\010\uffdc\011\uffdc\012\uffdc\032\uffdc\037\uffdc" +
    "\044\uffdc\001\002\000\004\037\231\001\002\000\004\042" +
    "\232\001\002\000\004\037\233\001\002\000\004\042\234" +
    "\001\002\000\004\037\235\001\002\000\004\042\236\001" +
    "\002\000\004\037\237\001\002\000\004\042\240\001\002" +
    "\000\004\037\241\001\002\000\004\042\242\001\002\000" +
    "\004\037\243\001\002\000\004\026\244\001\002\000\004" +
    "\034\245\001\002\000\022\004\uffde\006\uffde\010\uffde\011" +
    "\uffde\012\uffde\032\uffde\037\uffde\044\uffde\001\002\000\004" +
    "\037\247\001\002\000\004\042\250\001\002\000\004\037" +
    "\251\001\002\000\004\042\252\001\002\000\004\037\253" +
    "\001\002\000\004\042\254\001\002\000\004\037\255\001" +
    "\002\000\004\042\256\001\002\000\004\037\257\001\002" +
    "\000\004\042\260\001\002\000\004\037\261\001\002\000" +
    "\004\042\262\001\002\000\004\037\263\001\002\000\004" +
    "\026\264\001\002\000\004\034\265\001\002\000\022\004" +
    "\uffe2\006\uffe2\010\uffe2\011\uffe2\012\uffe2\032\uffe2\037\uffe2" +
    "\044\uffe2\001\002\000\004\037\267\001\002\000\004\042" +
    "\270\001\002\000\004\037\271\001\002\000\004\042\272" +
    "\001\002\000\004\037\273\001\002\000\004\042\274\001" +
    "\002\000\004\037\275\001\002\000\004\042\276\001\002" +
    "\000\004\037\277\001\002\000\004\042\300\001\002\000" +
    "\004\037\301\001\002\000\004\042\302\001\002\000\004" +
    "\037\303\001\002\000\004\042\304\001\002\000\004\037" +
    "\305\001\002\000\004\042\306\001\002\000\004\037\307" +
    "\001\002\000\004\042\310\001\002\000\004\037\311\001" +
    "\002\000\004\026\312\001\002\000\004\034\313\001\002" +
    "\000\022\004\uffe1\006\uffe1\010\uffe1\011\uffe1\012\uffe1\032" +
    "\uffe1\037\uffe1\044\uffe1\001\002\000\004\037\315\001\002" +
    "\000\004\042\316\001\002\000\004\037\317\001\002\000" +
    "\004\042\320\001\002\000\004\037\321\001\002\000\004" +
    "\042\322\001\002\000\004\037\323\001\002\000\004\042" +
    "\324\001\002\000\004\037\325\001\002\000\004\042\326" +
    "\001\002\000\004\037\327\001\002\000\004\042\330\001" +
    "\002\000\004\037\331\001\002\000\004\042\332\001\002" +
    "\000\004\037\333\001\002\000\004\026\334\001\002\000" +
    "\004\034\335\001\002\000\022\004\uffdf\006\uffdf\010\uffdf" +
    "\011\uffdf\012\uffdf\032\uffdf\037\uffdf\044\uffdf\001\002\000" +
    "\004\037\337\001\002\000\004\030\340\001\002\000\004" +
    "\035\341\001\002\000\012\014\052\036\061\037\056\043" +
    "\060\001\002\000\004\034\343\001\002\000\022\004\ufff0" +
    "\006\ufff0\010\ufff0\011\ufff0\012\ufff0\032\ufff0\037\ufff0\044" +
    "\ufff0\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\341\000\012\003\005\004\007\005\006\006\003\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\023\015\001\001\000\002\001\001\000\022\007" +
    "\031\010\017\011\022\012\034\013\030\014\024\015\027" +
    "\021\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\120\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\010\044\011\022" +
    "\012\034\013\030\014\024\015\027\021\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\016\061\022" +
    "\056\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\071\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\110\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\116\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\017\122\001\001\000" +
    "\002\001\001\000\004\022\130\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\341\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$C3dCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$C3dCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$C3dCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automaticamente ante algun error sintáctico.*/
    public void syntax_error(Symbol s)
    {
        System.out.println("Error sintactico en la Fila " + (s.right+1) +" Columna "+s.left+ ". Identificador \"" +s.value + "\" no reconocido." );
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    { 
        System.out.println("Error sintactico en la Fila " + (s.right+1)+ " Columna "+s.left+". Identificador \"" + s.value + "\" no reconocido."); 
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$C3dCup$actions {


    int instruccionActual = 0;

  private final C3dCup parser;

  /** Constructor */
  CUP$C3dCup$actions(C3dCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$C3dCup$do_action(
    int                        CUP$C3dCup$act_num,
    java_cup.runtime.lr_parser CUP$C3dCup$parser,
    java.util.Stack            CUP$C3dCup$stack,
    int                        CUP$C3dCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$C3dCup$result;

      /* select the action based on the action number */
      switch (CUP$C3dCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // OP_COMPARADOR ::= tdiferente 
            {
              Object RESULT = null;
		 RESULT = new String ("!="); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // OP_COMPARADOR ::= tigualigual 
            {
              Object RESULT = null;
		 RESULT = new String ("=="); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // OP_COMPARADOR ::= tmayorigual 
            {
              Object RESULT = null;
		 RESULT = new String (">="); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // OP_COMPARADOR ::= tmenorigual 
            {
              Object RESULT = null;
		 RESULT = new String ("<="); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // OP_COMPARADOR ::= tmayor 
            {
              Object RESULT = null;
		 RESULT = new String (">"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // OP_COMPARADOR ::= tmenor 
            {
              Object RESULT = null;
		 RESULT = new String ("<"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(13/*OP_COMPARADOR*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // OP_ARITMETICO ::= tpotencia 
            {
              Object RESULT = null;
		 RESULT = new String ("^"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(14/*OP_ARITMETICO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // OP_ARITMETICO ::= tdividir 
            {
              Object RESULT = null;
		 RESULT = new String ("/"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(14/*OP_ARITMETICO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // OP_ARITMETICO ::= tpor 
            {
              Object RESULT = null;
		 RESULT = new String ("*"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(14/*OP_ARITMETICO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // OP_ARITMETICO ::= tmenos 
            {
              Object RESULT = null;
		 RESULT = new String ("-"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(14/*OP_ARITMETICO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // OP_ARITMETICO ::= tmas 
            {
              Object RESULT = null;
		 RESULT = new String ("+"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(14/*OP_ARITMETICO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // GOTO ::= tgoto tiden tpuntocoma 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 Goto go = new Goto((String)id); RESULT = go; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(8/*GOTO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // IF ::= tif VAL_UNI OP_COMPARADOR VAL_UNI tthen tgoto tiden tpuntocoma 
            {
              Object RESULT = null;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-5)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-5)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-5)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 SentenciaIF sentIF = new SentenciaIF((Instruccion)v1, (String)op, (Instruccion)v2, (String)id); RESULT = sentIF; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(11/*IF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-7)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // ETIQUETA ::= tiden tdospuntos 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 MetodosTS.saveEtiqueta((String)e, instruccionActual); RESULT = new Etiqueta(); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(7/*ETIQUETA*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // CALLF ::= tcallf ttexto tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Texto tex = new Texto((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6); RESULT = tex; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-15)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // CALLF ::= tcallf tlienzo tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Lienzo lie = new Lienzo((String)id1, (String)id2, (String)id3, (String)id4, (String)id5); RESULT = lie; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-13)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // CALLF ::= tcallf tpoligono tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Poligono pol = new Poligono((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6); RESULT = pol; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-15)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // CALLF ::= tcallf tovalo tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id7left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id7right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id7 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id8left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id8right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id8 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Ovalo ova = new Ovalo((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6, (String)id7, (String)id8); RESULT = ova; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-19)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CALLF ::= tcallf trectangulo tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id7left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id7right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id7 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id8left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id8right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id8 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Rectangulo rec = new Rectangulo((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6, (String)id7, (String)id8); RESULT = rec; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-19)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // CALLF ::= tcallf tarco tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-20)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-20)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-20)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-18)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-18)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-18)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-16)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id7left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id7right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id7 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id8left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id8right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id8 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id9left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id9right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id9 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id10left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id10right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id10 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Arco arc = new Arco((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6, (String)id7, (String)id8, (String)id9, (String)id10); RESULT = arc; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-23)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // CALLF ::= tcallf tlinea tpa tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tcoma tiden tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-14)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-12)).value;
		int id3left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).left;
		int id3right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).right;
		Object id3 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-10)).value;
		int id4left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).left;
		int id4right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).right;
		Object id4 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-8)).value;
		int id5left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int id5right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id5 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int id6left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id6right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id6 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int id7left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int id7right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id7 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Linea lin = new Linea((String)id1, (String)id2, (String)id3, (String)id4, (String)id5, (String)id6, (String)id7); RESULT = lin; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-17)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // CALLF ::= tcallf timprimir tpa tiden tcoma tentero tpc tpuntocoma 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		 Imprimir imp = new Imprimir((String)id1, (String)e1); RESULT = imp; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(10/*CALLF*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-7)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // CALL ::= tcall tiden tpa tpc tpuntocoma 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).value;
		 Call cal = new Call((String)id); RESULT = cal; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(15/*CALL*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // VAL_UNI ::= tmenos tdecimal 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 Numero num = new Numero("-"+(String)e); RESULT = num; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(16/*VAL_UNI*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // VAL_UNI ::= tmenos tentero 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 Numero num = new Numero("-"+(String)e); RESULT = num; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(16/*VAL_UNI*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // VAL_UNI ::= tiden 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 ValorVariable valVar = new ValorVariable((String)e); RESULT = valVar; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(16/*VAL_UNI*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // VAL_UNI ::= tdecimal 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 Numero num = new Numero((String)e); RESULT = num; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(16/*VAL_UNI*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // VAL_UNI ::= tentero 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 Numero num = new Numero((String)e); RESULT = num; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(16/*VAL_UNI*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXPRESION ::= tfloattoint tpa VAL_UNI tpc 
            {
              Object RESULT = null;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 FloatToInt flo = new FloatToInt((Instruccion)v1); RESULT = flo; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPRESION ::= tconca tpa tiden tcoma tiden tpc 
            {
              Object RESULT = null;
		int id1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 Concatenar conc = new Concatenar((String)id1, (String)id2); RESULT = conc; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-5)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXPRESION ::= VAL_UNI OP_ARITMETICO VAL_UNI 
            {
              Object RESULT = null;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 Operacion oper = new Operacion((Instruccion)v1, (String)op, (Instruccion)v2); RESULT = oper; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EXPRESION ::= VAL_UNI 
            {
              Object RESULT = null;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 RESULT = v1; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EXPRESION ::= theap tca tiden tcc 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 ValorHeap valheap = new ValorHeap((String)id); RESULT = valheap; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // EXPRESION ::= tstack tca tiden tcc 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 ValorStack valstack = new ValorStack((String)id); RESULT = valstack; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(12/*EXPRESION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ASIGNACION ::= theap tca tiden tcc tigual VAL_UNI tpuntocoma 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 Asignacion asig = new Asignacion(2, (String)id, (Instruccion)v1); RESULT = asig; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(9/*ASIGNACION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ASIGNACION ::= tstack tca tiden tcc tigual VAL_UNI tpuntocoma 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-4)).value;
		int v1left = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 Asignacion asig = new Asignacion(1, (String)id, (Instruccion)v1); RESULT = asig; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(9/*ASIGNACION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ASIGNACION ::= tiden tigual EXPRESION tpuntocoma 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 Asignacion asig = new Asignacion(0, (String)id, (Instruccion)ex); RESULT = asig; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(9/*ASIGNACION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // INSTRUCCION ::= GOTO 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // INSTRUCCION ::= IF 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // INSTRUCCION ::= ETIQUETA 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // INSTRUCCION ::= CALLF 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // INSTRUCCION ::= CALL 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INSTRUCCION ::= ASIGNACION 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 instruccionActual++; RESULT = e; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(6/*INSTRUCCION*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INSTRUCCIONES ::= INSTRUCCION 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		  ArrayList<Instruccion> lista = new ArrayList<>();
                                                                                if(e!=null){lista.add((Instruccion)e);}
                                                                                RESULT = lista;
                                                                                
              CUP$C3dCup$result = new java_cup.runtime.Symbol(5/*INSTRUCCIONES*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INSTRUCCIONES ::= INSTRUCCIONES INSTRUCCION 
            {
              Object RESULT = null;
		int lileft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object li = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		 ArrayList<Instruccion> lista = (ArrayList<Instruccion>)li;
                                                                                if(e!=null){lista.add((Instruccion)e);}
                                                                                RESULT = lista;
                                                                                
              CUP$C3dCup$result = new java_cup.runtime.Symbol(5/*INSTRUCCIONES*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // METODO ::= tmethod tiden tpa tpc NT$0 tla INSTRUCCIONES tlc 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-6)).value;
		int lileft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object li = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		 
                    Metodo met = new Metodo((String)id, (ArrayList<Instruccion>)li); 
                    MetodosTS.TablaMetodos.put((String)id, met);
                    
              CUP$C3dCup$result = new java_cup.runtime.Symbol(4/*METODO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-7)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-2)).value;
 instruccionActual=0; 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(17/*NT$0*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // METODOS ::= METODO 
            {
              Object RESULT = null;
		  
              CUP$C3dCup$result = new java_cup.runtime.Symbol(3/*METODOS*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // METODOS ::= METODOS METODO 
            {
              Object RESULT = null;
		  
              CUP$C3dCup$result = new java_cup.runtime.Symbol(3/*METODOS*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CUERPO ::= METODOS 
            {
              Object RESULT = null;
		  
              CUP$C3dCup$result = new java_cup.runtime.Symbol(2/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CUERPO 
            {
              Object RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).value;
		System.out.println("Fin C3D"); 
              CUP$C3dCup$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          return CUP$C3dCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).value;
		RESULT = start_val;
              CUP$C3dCup$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-1)).left, ((java_cup.runtime.Symbol)CUP$C3dCup$stack.elementAt(CUP$C3dCup$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$C3dCup$parser.done_parsing();
          return CUP$C3dCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

